---
title: "Project Milestone 3"
author: "Peter Ward, Hayes Waddell, Nathan Gumagay"
format: html
editor: visual
---

#Our Blog Post


  As a team we believe that our research questions could have a huge impact on future pitcher analysis and performance. We hypothesized that limiting opponents bat speed is one of the most important factors in determining pitcher's performance. Thus, analyzing pitchers' bat speed against is significant in determining their future outlook, as higher bat speeds against are correlated with higher exit velocities against, and higher exit velocities against are correlated with lower performance stats. To provide a bit of context: swing speed is how fast a batter swings at a pitch calculated in miles per hour. The faster a batter's swing speed, the more force they will apply to the ball if they make contact. The more force a batter applies to a ball, the faster the exit velocity of the ball off the bat will be (also in miles per hour). And the higher the exit velocity of a ball, the further it will travel and the greater the odds that no fielder will be able to catch it for an out. Thus, a batter swinging faster results in them hitting the ball harder which results in more negative outcomes for the pitcher, so it is in a pitcher's best interest to influence the batter to decrease their bat speed. This is why we believe the outcomes of our analysis will be of significance to pitchers.
  
  The specific focus of our project lies in determining if there is any variation in batters' swing speeds depending on the pitcher. If there is, we wanted to locate the underlying cause of that variation. Using our prior knowledge of baseball we narrowed our scope of potential causal variables to include Statcast pitcher metrics like pitch velocity, spin and break. Before starting our project we hypothesized that one of these metrics would be what causes some pitchers to be so effective in limiting bat speeds, and others to be less effective. We made this determination because we know as hitters that the only factor that changes how hard we swing is how we perceive the pitch as it is coming towards us. Pitch metrics such as velocity and spin alter our perception of the pitch, and therefore our swing speed. Therefore, we decided to focus on pitch metrics in our analysis.
  
  To address this we created visualizations for each of these metrics, highlighting the differences in each metric between two groups: a group of pitchers that cause batters to swing slower than their average swing speeds, and a group of pitchers that cause batters to swing faster than their average swing speeds. Initially we calculated the average bat speed for every hitter in our data set. Then, we calculated the difference between the bat speed in each of a hitter's respective plate appearances and their mean bat speed. Then, we grouped the dataset by pitcher to calculate the mean of the respective differences in average bat speed and per plate appearance bat speed for each pitcher. Using this data, we created two sub datasets: one consisting of the 25 pitchers that created the highest differential bat speed and one for the 25 pitchers that created the lowest. We constructed these data sets to find important differences in each of the metrics between the two groups, since we hypothesized that one of these metrics is what caused the pitchers to have varying levels of success in limiting bat speeds. More specifically, these visualizations allowed us to focus on the metric results for the pitchers that were able to limit batters' swing speeds relative to their average to determine what they were doing differently from the other pitchers. Moreover, in each visualization we included each pitch type because we theorized that different pitches ellicit different reactions out of the hitter, and thus influence bat speed in different ways.

  From the velocity visualization we learned that an inverse relationship between the pitch velocity and swing speed exists across most pitch types in the group of pitchers that limited opponents' bat speeds. Through our spin rate visualization we found that the group of pitchers that are effective in slowing down bat speed throw pitches that break downwards with less spin, and pitches that break horizontally with more spin. Thus, we concluded that the impact of spin rate on batters' swing speed depends on the type of pitch being thrown. After analyzing the visualization of perceived vs actual velocity, we determined that the pitchers that limited opposing bat speeds threw pitches that had a greater perceived velocity than actual velocity. Lastly, the horizontal break visualization taught us that the pitchers with more horizontal break on most of their specific pitches produced slower bat speeds. Then, with the vertical break visualization, we found that the pitchers with less vertical break on their pitches produced slower bat speeds.
  
  Overall, this lead us to conclude that there is a substantial difference in batters' swing speeds across different pitchers, and that a pitcher seeking to be effective in limiting opponents bat speed should throw their pitches with more velocity, higher spin, more horizontal break, less vertical break and more perceived velocity. We have yet to determine which of these factors is the most significant and the extent to which eliciting slower bat speeds contributes to a pitcher's success, as well as if any confounding factors exist that could also be influencing swing speeds. We also need to determine what statistic is the most representative of pitcher success. We will use our second data set to carry out these analyses in the future. 
  
  One limitation of our dataset that we must acknowledge is that it only contains data from the first half of the 2024 season, which leaves a high possibility of outcomes having high variance from a player's normal outcomes throughout the course of an entire season. It also gives us less data observations to work with than we would have if our dataset consisted of season-long data. Furthermore, there are no ethical considerations with our data because our data is public and the site we acquired it from has player consent as well as league consent. We believe the conclusions of our analysis will be helpful for pitchers by allowing them to improve their performance, so it is ethical for us to carry out this project.
