---
title: "Project Milestone 3"
author: "Peter Ward, Hayes Waddell, Nathan Gumagay"
format: html
editor: visual
---

#Our Blog Post


  As a team we believe that our research questions will have a huge importance into how the future pitcher could be shaped. Seeing the results of the hitting side while pairing it up with certain pitches and the metrics behind the pitch. We believe that certain hitting metrics correlate with pitcher success. Attaining this information about pitcher metrics influence on hitters allows us to determine the pitcher's outlook on performance with their current data. We think that bat speed is one of the most important indicator's of a pitcher's ability to perform well. Looking at their bat speed against is significant for predicting a pitcher's future outlook. 

  The specific focus of our project is determining if there is variation in batter's swing speed depending on the pitcher. Then, locating the underlying cause of that variation. Using our prior knowledge of baseball we narrowed our scope to include certain metrics like pitcher speed, spin and break. Before starting our project we hypothesized the importance of these metrics with pitcher influence on hitter outcome. 

  To address this we created visualizations for each of these metrics highlighting the differences in bat speed when influenced by a specific metric. Initially we calculated the average bat speed for every hitter in our data set. Then, calculated the difference between the bat speed in each of their respective plate appearances and their mean bat speed. Using that data to create the mean of their respective differences in average bat speed and per each plate appearance bat speed.  Using this data we created two sub data sets, one consisting of the 25 pitchers that created the highest differential bat speed and then one for the 25 pitchers that created the lowest. We constructed each of these data sets to find important differences in each of the metric. In each visualization we wanted to look at each pitch type because different pitches have different impacts on the hitter. 

  By making specific visualizations for each of the metrics. This allowed us to draw surface conclusions as to what will be potential solutions to our question. Mainly, we wanted to focus on the metric results for the pitchers that were able to limit bat speeds relative to their average. From the velocity visualization we learned that a pitcher's velocity has an impact on the hitter's bat speed. Specifically an inverse correlation between the pitch speed and swing speed across most pitch types. Through our spin rate visualization we found that in the group of pitchers that are effective in slowing down bat speed. The pitches that break downwards have lower spin rates, while pitches that break horizontally have more spin. Making the visualization of perceived vs actual velocity, the slowest bat speeds occur in most of the pitch types, when the hitter perceived the pitch as faster. The horizontal break visualization taught us that the pitchers with more horizontal break on most of their specific pitches produced slower bat speeds. Then, with the vertical break visualization, we found that the pitches with less vertical break produced slower bat speeds (excluding splitters). 

  Overall, this leads us to conclude that a pitcher seeking to be effective in limiting opponents bat speed should throw their pitcher with more velocity, high spin, more horizontal break, less vertical break and more percieved velocity. We have yet to determine which of these factors is the most significant and also try and find if the slow bat speed contributes to pitcher's success. We will use our second data set to carry out the analysis of pitcher's success in the future. One limitation of our dataset that we must acknowledge is that it only contains data from the first half of the 2024 season which leaves a high possibility of variance data. There are no ethical considerations because our data is public and the site has player consent as well as league consent. Furthermore, we believe the conclusions of our analysis will be helpful for pitchers and that it is ethical to want to carry out this project.






